@startuml
' Creates a entity with a colorized sprite and stereotype
' Params:
'   e_type:     the entity type (e.g. component, node, agent, etc.)
'   e_color:    the color for the sprite
'   e_sprite:   the sprite for the AWS Icon representing the entity
'   e_stereo:   the stereotype, which can define additional styling
!define AWS_ENTITY(e_type,e_color,e_sprite,e_stereo) e_type "<color:e_color><$e_sprite></color>" <<e_stereo>>

' Creates a entity with a colorized sprite, title, and stereotype
' Params:
'   e_type:     the entity type (e.g. component, node, agent, etc.)
'   e_color:    the color for the sprite
'   e_sprite:   the sprite for the AWS Icon representing the entity
'   e_title:    the title to display under the sprite
'   e_stereo:   the stereotype, which can define additional styling
!define AWS_ENTITY(e_type,e_color,e_sprite,e_title,e_stereo) e_type "<color:e_color><$e_sprite></color>\r e_title" <<e_stereo>>

skinparam cloudBackgroundColor<<AWS>> White

@enduml
