@startuml
sprite $AWSOpsWorks [70x84/16] {
0000000000000000000000000000000000FC0000000000000000000000000000000000
00000000000000000000000000000000FFFCCC00000000000000000000000000000000
000000000000000000000000000000FFFFFCCCCC000000000000000000000000000000
0000000000000000000000000000FFFFFFFCCCCCCC0000000000000000000000000000
00000000000000000000000000FFFFFFFFFCCCCCCCCC00000000000000000000000000
000000000000000000000000FFFFFFFFFFFCCCCCCCCCCC000000000000000000000000
0000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC0000000000000000000000
00000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
000000000000000000FFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCC000000000000000000
00000000000000000FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCC00000000000000000
00000000000000000FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCC00000000000000000
00000000000000000FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCC00000000000000000
000000000000000000FFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCC000000000000000000
00000000FFFCCCC000FFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCC000FFFFCCC00000000
000000FFFFFECCCCCC0FFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCC0FFFFFFECCCCC000000
0000FFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCC0000
00FFFFFFFFFFECCCCCCCEFFFFFFFFFFFFFFCCCCCCCCCCCCCCEFFFFFFFDCCCCCCCCCC00
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCCCCC
FFFFFFFFFFFFFECCCCCCCDFFFFFFFFFFFFFCCCCCCCCCCCCCEFFFFFFFDCCCCCCCCCCCCC
FFFFFFFFFFFFFFDCCCCCCCEFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFECCCCCCCCCCCCCC
FFFFFFFFFFFFFFECCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCEFFFFFFFDCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFDCCCCCCCEFFFFFFFFFFFCCCCCCCCCCCDFFFFFFFECCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFDCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFDCCCCCCCEFFFFFFFFFFCCCCCCCCCCDFFFFFFFECCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFDCCCCCCCDFFFFFFFFFCCCCCCCCCEFFFFFFFECCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFECCCCCCCDFFFFFFFFCCCCCCCCEFFFFFFFECCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFCCCCCCCCEFFFFFFFCCCCCCCDFFFFFFFFCCCCCCCCCCCCCCCCCCC
0FFFFFFFFFFFFFFFFFFECCCCCCCDFFFFFFFCCCCCCCEFFFFFFFECCCCCCCCCCCCCCCCCC0
0FFFFFFFFFFFFFFFFFFFCCCCCCCCEFFFFFFCCCCCCDFFFFFFFFCCCCCCCCCCCCCCCCCCC0
00FFFFFFFFFFFFFFFFFFECCCCCCCCFFFFFFCCCCCCFFFFFFFFDCCCCCCCCCCCCCCCCCC00
00FFFFFFFFFFFFFFFFFFFCCCCCCCCEFFFFFCCCCCEFFFFFFFFCCCCCCCCCCCCCCCCCCC00
00FFFFFFFFFFFFFFFFFFFECCCCCCCCFFFFFCCCCCFFFFFFFFDCCCCCCCCCCCCCCCCCCC00
000FFFFFFFFFFFFFFFFFFFDCCCCCCCDFFFFCCCCEFFFFFFFECCCCCCCCCCCCCCCCCCC000
000FFFFFFFFFFFFFFFFFFFECCCCCCCCFFFFCCCCFFFFFFFFDCCCCCCCCCCCCCCCCCCC000
000FFFFFFFFFFFFFFFFFFFFDCCCCCCCDFFFCCCEFFFFFFFECCCCCCCCCCCCCCCCCCCC000
0000FFFFFFFFFFFFFFFFFFFFCCCCCCCCEFFCCDFFFFFFFFCCCCCCCCCCCCCCCCCCCC0000
0000FFFFFFFFFFFFFFFFFFFFDCCCCCCCDFFCCFFFFFFFFECCCCCCCCCCCCCCCCCCCC0000
0000FFFFFFFFFFFFFFFFFFFFFCCCCCCCCEFCDFFFFFFFFCCCCCCCCCCCCCCCCCCCCC0000
00000FFFFFFFFFFFFFFFFFFFFDCCCCCCCCFCFFFFFFFFECCCCCCCCCCCCCCCCCCCC00000
00000FFFFFFFFFFFFFFFFFFFFFCCCCCCCCEEFFFFFFFFCCCCCCCCCCCCCCCCCCCCC00000
FDCCCDFFFFFFFFFFFFFFFFFFFFECCCCCCCCEFFFFFFFECCCCCCCCCCCCCCCCCCCCFFFFFC
FECCCCFFFFFFFFFFFFFFFFFFFFFCCCCCCCCEFFFFFFFCCCCCCCCCCCCCCCCCCCCCFFFFDC
FFCCCCDFFFFFFFFFFFFFFFFFFFFECCCCCCCEFFFFFFDCCCCCCCCCCCCCCCCCCCCEFFFFCC
FFDCCCCFFFFFFFFFFFFFFFFFFFFFCCCCCCCEFFFFFFCCCCCCCCCCCCCCCCCCCCCFFFFFCC
FFECCCCFFFFFFFFFFFFFFFFFFFFFECCCCCCEFFFFFDCCCCCCCCCCCCCCCCCCCCDFFFFDCC
FFFCCCCDFFFFFFFFFFFFFFFFFFFFFCCCCCCEFFFFFCCCCCCCCCCCCCCCCCCCCCEFFFFCCC
FFFDCCCCFFFFFFFFFFFFFFFFFFFFFECCCCCEFFFFDCCCCCCCCCCCCCCCCCCCCCFFFFFCCC
FFFECCCCFFFFFFFFFFFFFFFFFFFFFFDCCCCEFFFECCCCCCCCCCCCCCCCCCCCCDFFFFDCCC
FFFFCCCCDFFFFFFFFFFFFFFFFFFFFFECCCCEFFFDCCCCCCCCCCCCCCCCCCCCCEFFFFDCCC
FFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFDCCCEFFECCCCCCCCCCCCCCCCCCCCCCFFFFFCCCC
FFFFDCCCCEFFFFFFFFFFFFFFFFFFFFFFCCCEFFCCCCCCCCCCCCCCCCCCCCCCDFFFFECCCC
FFFFFCCCCDFFFFFFFFFFFFFFFFFFFFFFDCCEFECCCCCCCCCCCCCCCCCCCCCCEFFFFDCCCC
FFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFCCEFCCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCC
FFFFFDCCCCEFFFFFFFFFFFFFFFFFFFFFFDCEECCCCCCCCCCCCCCCCCCCCCCDFFFFECCCCC
FFFFFFCCCCDFFFFFFFFFFFFFFFFFFFFFFFCECCCCCCCCCCCCCCCCCCCCCCCEFFFFDCCCCC
FFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFEDCCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCC
FFFFFFDCCCCEFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCDFFFFECCCCCC
FFFFFFFCCCCDFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCEFFFFDCCCCCC
FFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCCC
FFFFFFFDCCCCEFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCDFFFFECCCCCCC
FFFFFFFFCCCCDFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCEFFFFDCCCCCCC
FFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCCCC
FFFFFFFFDCCCCEFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCDFFFFECCCCCCCC
FFFFFFFFFCCCCDFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCFFFFFDCCCCCCCC
FFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCCCCC
00FFFFFFFDCCCCEFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCDFFFFECCCCCCC00
0000FFFFFFCCCCDFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCFFFFFDCCCCC0000
000000FFFFCCCCCFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCDFFFFFCCCC000000
00000000FFDCCC0FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCC0FFFECC00000000
000000000000000FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCC000000000000000
0000000000000000FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCC0000000000000000
0000000000000000FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCC0000000000000000
0000000000000000FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCC0000000000000000
000000000000000000FFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCC000000000000000000
00000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC0000000000000000000000
000000000000000000000000FFFFFFFFFFFCCCCCCCCCCC000000000000000000000000
00000000000000000000000000FFFFFFFFFCCCCCCCCC00000000000000000000000000
0000000000000000000000000000FFFFFFFCCCCCCC0000000000000000000000000000
000000000000000000000000000000FFFFFCCCCC000000000000000000000000000000
00000000000000000000000000000000FFFCCC00000000000000000000000000000000
0000000000000000000000000000000000EC0000000000000000000000000000000000
}


!define AWSOPSWORKS(alias) AWS_ENTITY(node,#769D3F,AWSOpsWorks,alias,AWSOpsWorks)

!define AWSOPSWORKS(alias,label) AWS_ENTITY(node,#769D3F,AWSOpsWorks,label,alias,AWSOpsWorks)

@enduml
