@startuml
!define AWS_PLANTUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/master

!includeurl AWS_PLANTUML/common.puml
!includeurl AWS_PLANTUML/StorageContentDelivery/S3/StorageContentDelivery_AmazonS3.puml
!includeurl AWS_PLANTUML/StorageContentDelivery/S3/StorageContentDelivery_AmazonS3_Bucket.puml

AWS_S3(s3) {
    S3_BUCKET(site,www.insecurity.co)
    S3_BUCKET(logs,logs.insecurity.co)
}
site .r.> logs : events
@enduml