@startuml
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/17-10-18/dist

!includeurl AWSPUML/common.puml
!includeurl AWSPUML/applicationservices/amazonapigateway/amazonapigateway.puml
!includeurl AWSPUML/compute/awslambda/awslambda.puml
!includeurl AWSPUML/compute/awslambda/lambdafunction/lambdafunction.puml
!includeurl AWSPUML/database/amazondynamodb/amazondynamodb.puml
!includeurl AWSPUML/database/amazondynamodb/table/table.puml
!includeurl AWSPUML/general/awscloud/awscloud.puml
!includeurl AWSPUML/general/client/client.puml
!includeurl AWSPUML/sdks/javascript/javascript.puml
!includeurl AWSPUML/general/user/user.puml
!includeurl AWSPUML/storage/amazons3/amazons3.puml
!includeurl AWSPUML/storage/amazons3/bucket/bucket.puml


skinparam componentArrowColor Black
skinparam componentBackgroundColor White
skinparam nodeBackgroundColor White
skinparam agentBackgroundColor White
skinparam artifactBackgroundColor White


USER(user)
CLIENT(browser)
JAVASCRIPT(js,SDK)

AWSCLOUD(aws) {

    AMAZONS3(s3) {
        BUCKET(site,www.insecurity.co)
        BUCKET(logs,logs.insecurity.co)
    }

    AMAZONAPIGATEWAY(api)

    AWSLAMBDA(lambda) {
        LAMBDAFUNCTION(addComments,addComments)
    }

    AMAZONDYNAMODB(dynamo) {
        TABLE(comments,Comments)
    }
}

user - browser

browser -d-> site :**1a**) get\nstatic\ncontent
site ~> logs :1a
site .u.> browser :**1b**
browser - js
js -r-> comments :**2a**) get\ncomments
comments ..> js :**2b**

js -r-> api :**3**) add\ncomment

api -d-> addComments :**4**

addComments -> comments :**5**

comments ..> js :**6**) new\ncomments
@enduml