@startuml

!define AWSPUML http://localhost:8000

!includeurl AWSPUML/common.puml
!includeurl AWSPUML/Storage-Content-Delivery/AmazonS3.puml

AMAZONS3(s3_internal)
AMAZONS3(s3_partner,Vendor's S3)

s3_internal <-- s3_partner

@enduml